<input type="hidden" name="all_number" value="<?php // echo $post_data;?>">
<div class="admin__page-section-title">
    <span class="title">Send SMS for this Order</span>
</div>
<div class="smsfield">
    <div class="smslabel">
        <span><b>SMS Text : </b></span>
    </div>
    <div>
        <textarea rows="5" cols="45" id="message_text" name="message_text" class="required-entry"></textarea>
    </div>
</div>
<div class="smstextrender">
    <div class="smstextrenderdata">
        <a href="javascript:void(0)" id="order_no" data->Order Number,</a>
        <a href="javascript:void(0)" id="customer_name" data->Customer Name,</a>
        <a href="javascript:void(0)" id="product_name" data->Product Name,</a>
        <a href="javascript:void(0)" id="payment_amount" data->Grand Total,</a>
    </div>
    <div class="smstextrenderdata" >
        <a href="javascript:void(0)" id="billing_name" data->Billing Name,</a>
        <a href="javascript:void(0)" id="shipping_name" data->Shipping Name,</a>
        <a href="javascript:void(0)" id="order_statu" data->Order Status,</a>
        <a href="javascript:void(0)" id="payment_method" data->Payment Method</a>
    </div>

</div>
<div class="sms_btn">
    <div id="modal">
        <button class="action tocart primary modalRun" type="submit" id="send_sms" >
            <span>Send SMS</span>
        </button>
    </div>
</div>
<br/>
<div id ="popup-mpdal"></div>
<?php 
$smsData = $block->getSmsData();

?>   
<div class="edit-order-comments" id="order_history_block">
        <ul class="note-list" id="order_Comment">
            <?php  
            foreach ($smsData as $key => $value) 
            {
            ?>
                <li class="note-list-item">       
                        <b>Send SMS</b>
                        <?php $date = date_create($value["updated_at"]); ?>
                        <span class="note-list-date"><?php echo date_format($date, 'F j, Y g:i:s A'); ?></span>
                        <div class="note-list-comment"><?php echo $value["sms_content"]; ?></div>
                </li>
            <?php
            }
            ?>
        </ul>
</div>


<script>
    require(['jquery','Magento_Ui/js/modal/modal'], function ($,modal) {
        var options = {
            type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'SMS sent successfully..',
                buttons: [{
                    text: $.mage.__('Ok'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };
        var option = {
            type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Please enter text to send SMS.',
                buttons: [{
                    text: $.mage.__('Ok'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };
        jQuery('document').ready(function () {
            jQuery("#send_sms").click('button.modalRun',function () {
                var msg_text = jQuery("#message_text").val();
                if (msg_text != "")
                {
                    jQuery("#send_sms").prop("disabled", true);
                    request = $.ajax({
                        url: "<?php echo $block->getPostformUrl(); ?>",
                        type: "post",
                        data: {"message": msg_text, "order_id":<?php echo $block->getOrderNumber() ?>, "order_test":0}
                    });

                    request.done(function (response, textStatus, jqXHR) {
                        jQuery("#send_sms").prop("disabled", false);
                        var popup = modal(options, $('#popup-mpdal'));
                        $('#popup-mpdal').modal('openModal');
                        $("#order_Comment").prepend('<li class="note-list-item" style="list-style-type:none; margin-bottom:10px;"><b>Send SMS </b><span class="note-list-date">'+response.datetime+'</span><div>'+response.smstext+'</div></li>');
                    });
                }
                else
                {
                    var popup = modal(option, $('#popup-mpdal'));
                    $('#popup-mpdal').modal('openModal');
                }
            });

            jQuery("#order_no").click(function () {
                var caretPos = document.getElementById("message_text").selectionStart;
                var textAreaTxt = jQuery("#message_text").val();
                var txtToAdd = "{{var order_no}}";
                jQuery("#message_text").val(textAreaTxt.substring(0, caretPos) + txtToAdd + textAreaTxt.substring(caretPos));  
            });
            jQuery("#customer_name").click(function () {
                var caretPos = document.getElementById("message_text").selectionStart;
                var textAreaTxt = jQuery("#message_text").val();
                var txtToAdd = "{{var customer_name}}";
                jQuery("#message_text").val(textAreaTxt.substring(0, caretPos) + txtToAdd + textAreaTxt.substring(caretPos));  
            });
            jQuery("#product_name").click(function () {
                var caretPos = document.getElementById("message_text").selectionStart;
                var textAreaTxt = jQuery("#message_text").val();
                var txtToAdd = "{{var product_name}}";
                jQuery("#message_text").val(textAreaTxt.substring(0, caretPos) + txtToAdd + textAreaTxt.substring(caretPos));  
            });
            jQuery("#payment_amount").click(function () {
                var caretPos = document.getElementById("message_text").selectionStart;
                var textAreaTxt = jQuery("#message_text").val();
                var txtToAdd = "{{var payment_amount}}";
                jQuery("#message_text").val(textAreaTxt.substring(0, caretPos) + txtToAdd + textAreaTxt.substring(caretPos));  
            });
            jQuery("#billing_name").click(function () {
                var caretPos = document.getElementById("message_text").selectionStart;
                var textAreaTxt = jQuery("#message_text").val();
                var txtToAdd = "{{var billing_name}}";
                jQuery("#message_text").val(textAreaTxt.substring(0, caretPos) + txtToAdd + textAreaTxt.substring(caretPos));  
            });
            jQuery("#shipping_name").click(function () {
                var caretPos = document.getElementById("message_text").selectionStart;
                var textAreaTxt = jQuery("#message_text").val();
                var txtToAdd = "{{var shipping_name}}";
                jQuery("#message_text").val(textAreaTxt.substring(0, caretPos) + txtToAdd + textAreaTxt.substring(caretPos));  
            });
            jQuery("#order_statu").click(function () {
                var caretPos = document.getElementById("message_text").selectionStart;
                var textAreaTxt = jQuery("#message_text").val();
                var txtToAdd = "{{var order_status}}";
                jQuery("#message_text").val(textAreaTxt.substring(0, caretPos) + txtToAdd + textAreaTxt.substring(caretPos));  
            });
            jQuery("#payment_method").click(function () {
                var caretPos = document.getElementById("message_text").selectionStart;
                var textAreaTxt = jQuery("#message_text").val();
                var txtToAdd = "{{var payment_method}}";
                jQuery("#message_text").val(textAreaTxt.substring(0, caretPos) + txtToAdd + textAreaTxt.substring(caretPos));  
            });
        });
    });
</script>
