<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/** @var \Amasty\Shopby\Block\Navigation\FilterRenderer\Category $block */
/** @var \Amasty\Shopby\Model\Layer\Filter\CategoryItems $filterItems */
/** @var \Amasty\Shopby\Model\Layer\Filter\Item $filterItem */
$filterItems = $block->getFilter()->getItems();
?>
<?php foreach ($filterItems->getItems($block->getPath()) as $filterItem) : ?>
    <?php $uniqId = uniqid(); ?>
    <?php $currentPath = ($block->getPath() ?: $filterItems->getStartPath()) . '/' . $filterItem->getValueString(); ?>
    <li class="item" data-label="<?= $block->escapeHtml($filterItem->getLabel()) ?>">
        <?php if ($filterItems->getItemsCount($block->getCurrentPath())) : ?>
            <span class="amshopby-category-collapse-icon"></span>
        <?php endif; ?>

        <?php if ($filterItem->getCount()) : ?>
            <?php $checked = $block->checkedFilter($filterItem) ? ' checked' : ''; ?>
            <a class="am_shopby_filter_item_<?= $block->escapeId($uniqId) ?>
               <?php if ($block->getFilter()->getItemsCount($currentPath)) : ?>
                    <?= "amshopby-filter-parent"; ?>
               <?php endif; ?>"
               href="<?= $block->escapeUrl($filterItem->getUrl()) ?>">
                <input
                        name="amshopby[<?= /* @escapeNotVerified */
                        $block->getFilter()->getRequestVar(); ?>][]"
                        value="<?= $block->escapeHtml($filterItem->getValueString()); ?>"
                        type="<?= $block->getInputType(); ?>"
                    <?= $checked ?>
                />
                <?= $filterItem->getLabel() ?>
                <?php if ($block->getFilterSetting()->isShowProductQuantities()) : ?>
                    <span class="count"><?= $filterItem->getCount() ?>
                        <span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1) : ?>
                                <?= $block->escapeHtml(__('item')) ?>
                            <?php else : ?>
                                <?= $block->escapeHtml(__('items')) ?>
                            <?php endif; ?>
                        </span>
                    </span>
                <?php endif; ?>
            </a>
        <?php else : ?>
            <?= $filterItem->getLabel() ?>
            <?php if ($block->getFilterSetting()->isShowProductQuantities()) : ?>
                <span class="count"><?= $filterItem->getCount() ?>
                    <span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1) : ?>
                            <?= $block->escapeHtml(__('item')) ?>
                        <?php else : ?>
                            <?= $block->escapeHtml(__('items')) ?>
                        <?php endif; ?>
                        </span>
                    </span>
            <?php endif; ?>
        <?php endif; ?>
        <script type="text/x-magento-init">
            {
                ".am_shopby_filter_item_<?= $block->escapeId($uniqId) ?>": {
                    "amShopbyFilterItemDefault": {
                        "collectFilters": <?= /* @escapeNotVerified */ $block->collectFilters(); ?>
                    }
                }
            }
        </script>
        <?php if ($block->getFilter()->getItemsCount($currentPath)): ?>
            <ol class="items items-children level-<?= $block->getLevel(); ?>">
                <?= $block->renderChildrenItems($currentPath); ?>
            </ol>
        <?php endif; ?>
    </li>
<?php endforeach; ?>