<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
    /** @var \Amasty\ShopbyBase\Model\FilterSetting $filterSetting */
    /** @var \Amasty\Shopby\Model\Layer\Filter\Item $filterItem */
    /** @var \Amasty\Shopby\Block\Navigation\FilterRenderer\Category $block */
    /** @var \Amasty\Shopby\Model\Layer\Filter\CategoryItems $filterItems */
    $filterItems = $block->getFilter()->getItems();
    $categoryHelper = $block->getCategoryHelper();
    $filterSetting = $block->getFilterSetting();
?>

<?php foreach ($filterItems->getItems($block->getPath()) as $filterItem) : ?>
    <?php $uniqId = uniqid(); ?>
    <?php $currentPath = ($block->getPath() ?: $filterItems->getStartPath()) . '/' . $filterItem->getValueString(); ?>
    <li class="item <?php if($block->getLevel() == '1'){ echo "parent-filter" ;} ?>" data-label="<?= $block->escapeHtml($filterItem->getLabel()) ?>">

        <?php $checked = $block->checkedFilter($filterItem) ? ' checked' : ''; ?>
            <a class="am_shopby_filter_item_<?= $block->escapeId($uniqId) ?>
                    <?php if ($block->isExpandByClick($currentPath)): ?>
                        <?= "amshopby-filter-parent" ?>
                    <?php endif; ?>"
                    href="<?= $block->escapeUrl($filterItem->getUrl()) ?>"
                    <?php if (!$filterSetting->isMultiselect()): ?>
                        <?= " forseload " ?>
                    <?php endif; ?>
            >
            <input
                    name="amshopby[<?= /* @escapeNotVerified */ $block->getFilter()->getRequestVar(); ?>][]"
                    value="<?= $block->escapeHtml($filterItem->getValueString()); ?>"
                    type="<?= $block->getInputType(); ?>"
                    id="<?= $block->escapeHtml($filterItem->getValueString()); ?>"
                <?= $checked ?>
            />
            <?php if ($block->getFilter()->useLabelsOnly()) : ?>
                <label 
					class="label"
					for="<?= $block->escapeHtml($filterItem->getValueString()); ?>"
					><?= $filterItem->getLabel() ?></label>
            <?php elseif ($block->getFilter()->useLabelsAndImages()) : ?>
                <span class="category-filter-image">
                    <img src="<?= $categoryHelper->getCategoryImageUrl($filterItem->getValue()) ?>"
                         title="<?= $filterItem->getLabel() ?>"
                         height="<?= $categoryHelper->getCategoryFilterImageSize(); ?>"
                         width="<?= $categoryHelper->getCategoryFilterImageSize(); ?>" />
                </span>
                <span class="label"><?= $filterItem->getLabel() ?></span>
            <?php else : ?>
                <span class="category-filter-image">
                    <img src="<?= $categoryHelper->getCategoryImageUrl($filterItem->getValue()) ?>"
                         title="<?= $filterItem->getLabel() ?>"
                         height="<?= $categoryHelper->getCategoryFilterImageSize(); ?>"
                         width="<?= $categoryHelper->getCategoryFilterImageSize(); ?>"/>
                </span>
            <?php endif; ?>
            <?php if ($filterSetting->isShowProductQuantities()) : ?>
                <span class="count"><?= $filterItem->getCount() ?>
                    <span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1) : ?>
                            <?= $block->escapeHtml(__('item')) ?>
                        <?php else : ?>
                            <?= $block->escapeHtml(__('items')) ?>
                        <?php endif; ?>
                    </span>
                </span>
            <?php endif; ?>
        </a>
	    <?php if ($block->isExpandByClick($currentPath)): ?>
            <span class="amshopby-category-collapse-icon"> </span>
        <?php endif; ?>
        <script type="text/x-magento-init">
            {
                ".am_shopby_filter_item_<?= $block->escapeId($uniqId) ?>": {
                    "amShopbyFilterCategoryLabelsFolding": {
                        "collectFilters": <?= /* @escapeNotVerified */ $block->collectFilters(); ?>
                    }
                }
            }

        </script>

        <?php if ($filterItems->getItemsCount($currentPath)): ?>
            <ol class="items items-children level-<?= $block->getLevel() ?>">
                <?= $block->renderChildrenItems($currentPath); ?>
            </ol>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
