<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /** @var $block \MageWorx\MultiFees\Block\Order\Info */ ?>
<div class="box-content">
    <div class="block block-order-details-view">
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo __('Additional Fees') ?></strong>
        </div>
        <div class="block-content">
            <?php foreach ($block->getFeeDetails() as $fees) { ?>
                <?php foreach ($fees as $fee) { ?>
                    <div class="box box-order-billing-address">
                        <strong class="box-title">
                            <span><?php echo $block->escapeHtml($fee['title']); ?></span>
                        </strong>
                        <div class="box-content">
                            <?php foreach ($fee['options'] as $optionId => $option) { ?>
                                <table>
                                    <tr>
                                        <td>
                                            <?php echo $block->escapeHtml($option['title']); ?>
                                            <?php echo $block->getOptionPriceHtml($option) ?>
                                        </td>
                                    </tr>
                                </table>
                            <?php } ?>
                        </div>
                        <?php echo $block->getFeeDateHtml($fee); ?>
                        <?php echo $block->getFeeMessageHtml($fee); ?>
                    </div>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
</div>