<?php

$_category  = $block->getCurrentCategory();
$collection = $block->getCollection($_category->getName());
//echo count($collection->getData());
$exist = count($collection->getData());
$blockObj = $block->getAbstractProductObj();
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('Promoted Products');
            $items = $collection;
            $limit = 12;
            $shuffle = 0;
            $canItemsAddToCart = true;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = null;
            $description = false;
            //echo '<pre>'; print_r($items->getData());
?>



<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php else: ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
    <?php endif; ?>
    <div class="block-title title">
        <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
        <?php if ($type == 'related' && $canItemsAddToCart): ?>
        <div class="block-actions">
            <?php /* @escapeNotVerified */ echo __('Check items to add to the cart or') ?>
            <button type="button" class="action select" role="select-all"><span><?php /* @escapeNotVerified */ echo __('select all') ?></span></button>
        </div>
        <?php endif; ?>
        <div class="products-slider products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
            <ol class="products list items">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                <?php 
                //$productObj = $block->getProductObj($_item->getId());?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($type == 'related' || $type == 'upsell'): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item" style="display: none;">' : '</li><li class="item product product-item" style="display: none;">' ?>
                <?php else: ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <?php endif; ?>
                <div class="product-item-info product-info <?php /* @escapeNotVerified */ echo $available; ?>">
					<div class=" product-item-images">
						<?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
						<a href="<?php /* @escapeNotVerified */ echo $blockObj->getProductUrl($_item) ?>" class="product photo product-item-photo">
							<?php echo $blockObj->getImage($_item, $image)->toHtml(); ?>
						</a>
						<?php if ($showWishlist || $showCompare): ?>
							<div class="add-to-links-secondary" data-role="add-to-links">
								<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
									<a href="#" data-post='<?php /* @escapeNotVerified */ echo $blockObj->getAddToWishlistParams($_item); ?>'  class="action wishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
										<span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
									</a>
								<?php endif; ?>
								<?php if ($blockObj->getAddToCompareUrl() && $showCompare): ?>
									<?php
									$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
									?>
									<a href="#" class="action compare"
									   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
									   data-role="add-to-links"
									   title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
										<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
									</a>
								<?php endif; ?>
							</div>
						<?php endif; ?>
						
						
					</div>
                    <div class="product-item-details">
                        <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $blockObj->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $blockObj->getProductUrl($_item) ?>">
                            <?php echo $blockObj->escapeHtml($_item->getName()) ?></a>
                        </strong>

                        <?php /* @escapeNotVerified */ echo $blockObj->getProductPrice($_item); ?>

                            <?php if ($templateType): ?>
                                <?php //echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <div class="field choice related">
                                        <input type="checkbox" class="checkbox related" id="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>" name="related_products[]" value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>" />
                                        <label class="label" for="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>"><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span></label>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>
							<div class="product-item-inner">
								<?php if ($showWishlist || $showCompare || $showCart): ?>
									<div class="product actions product-item-actions">
										<?php if ($showCart): ?>
											<div class="add-to-cart-primary">
												<?php if ($_item->isSaleable()): ?>
													<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
														<button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $blockObj->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
															<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
														</button>
													<?php else: ?>
														<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
														$postData = $postDataHelper->getPostData($blockObj->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
														?>
														<button class="action tocart primary"
																data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
																type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
															<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
														</button>
													<?php endif; ?>
												<?php else: ?>
													<?php if ($_item->getIsSalable()): ?>
														<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
											<?php echo $blockObj->getProductDetailsHtml($_item); ?>
										<?php endif; ?>
										
										
									</div>
								<?php endif; ?>
							
							</div>
                        </div>
                    </div>
                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif;?>

<script type="text/javascript">
require([
  "jquery",
  "owlcarousel/minjs"
 ], function($,owlCarousel){
   	
      $(".products-slider ol").owlCarousel({
   		items : 4,
		itemsDesktop : [1200,4],
   		itemsDesktopSmall : [992,3],
   		itemsTablet: [767,2],
   		itemsMobile : [400,1],
   		autoPlay : false,
   		slideSpeed : 1000,
   		navigation : true,
   		stopOnHover : true,
   		pagination : false
      });
      
   });
</script>
