<div class="main-container">
	<?php echo $block->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('Plazathemes_Bannerslider::bannerslider.phtml')->toHtml();?>
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('products_category_home1')->toHtml(); ?>
	<div class="banner-text1-home1">
		<div class="container-inner">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_text1_home1')->toHtml(); ?>
		</div>
	</div>
	<?php echo $block->getLayout()->createBlock('Plazathemes\Pricecountdown\Block\Pricecountdown')->setTemplate('Plazathemes_Pricecountdown::saleslider.phtml')->toHtml();?>
	<div class="banner-text2-home1">
		<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_text2_home1')->toHtml(); ?>
	</div>
	<div class="banner-text3-home1">
		<div class="container-inner">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_text3_home1')->toHtml(); ?>
		</div>
	</div>
	<div class="ma-testimonial">
			<?php echo $block->getLayout()->createBlock('Plazathemes\Testimonial\Block\Testimonial')->setTemplate('Plazathemes_Testimonial::testimonial.phtml')->toHtml();?>
	</div>
	<div class="ma-blog">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('Plazathemes_Blog::sidebar/slider.phtml')->toHtml();?>
	</div>
	<div class="container-inner">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Brandslider\Block\Brandslider')->setTemplate('Plazathemes_Brandslider::brandslider.phtml')->toHtml();?>
		<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_images1_home1')->toHtml(); ?>
	</div>
</div>


