<div class="main-container">
	<?php echo $block->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('Plazathemes_Bannerslider::bannerslider.phtml')->toHtml();?>
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_images1_home2')->toHtml(); ?>
	<div class="ma-slider">
		<?php echo $block->getLayout()->createBlock('Amasty\ShopbyBrand\Block\Widget\BrandSlider')->setTemplate('Amasty_ShopbyBrand::widget/brand_list/slider.phtml')->toHtml();?>
	</div>
	
	<?php echo $block->getLayout()->createBlock('Plazathemes\Producttab\Block\Producttab')->setTemplate('Plazathemes_Producttab::producttab.phtml')->toHtml();?>
	
	
	<div class="ma-time">
		<div class="container-inner">
			<div class="row">
				<div class="col-sm-8">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Pricecountdown\Block\Pricecountdown')->setTemplate('Plazathemes_Pricecountdown::saleslider.phtml')->toHtml();?>
				</div>
				<div class="col-sm-4">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Newproductslider\Block\Newproductslider')->setTemplate('Plazathemes_Newproductslider::newproductslider.phtml')->toHtml();?>
				</div>
			</div>
		</div>
	</div>
	<div class="container-inner">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Featureproductslider\Block\Featureproductslider')->setTemplate('Plazathemes_Featureproductslider::featureproductslider.phtml')->toHtml();?>
	</div>
	
	<div class="ma-testimonial">
		<div class="container-inner">
			<?php echo $block->getLayout()->createBlock('Plazathemes\Testimonial\Block\Testimonial')->setTemplate('Plazathemes_Testimonial::testimonial.phtml')->toHtml();?>
		</div>
	</div>

	<div class="container-inner">
		<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('Plazathemes_Blog::sidebar/slider.phtml')->toHtml();?>
		<?php echo $block->getLayout()->createBlock('Plazathemes\Brandslider\Block\Brandslider')->setTemplate('Plazathemes_Brandslider::brandslider.phtml')->toHtml();?>
	</div>
</div>


